name: Deploy node exporter

inputs:
  # ssh
  ssh-host:
    required: true
  ssh-username:
    required: true
  ssh-port:
    required: true
  ssh-key:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy node exporter
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.ssh-host }}
        USERNAME: ${{ inputs.ssh-username }}
        PORT: ${{ inputs.ssh-port }}
        KEY: ${{ inputs.ssh-key }}
        script: |
          docker run -d \
          --name="monitoring-node-exporter" \
          --net="host" \
          --pid="host" \
          -v "/:/host:ro,rslave" \
          --restart=always \
          quay.io/prometheus/node-exporter:v1.7.0 \
          --path.rootfs=/host
