name: Stop old containers

inputs:
  # ssh
  ssh-host:
    required: true
  ssh-username:
    required: true
  ssh-port:
    required: true
  ssh-key:
    required: true

  names:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Stop old containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.ssh-host }}
        USERNAME: ${{ inputs.ssh-username }}
        PORT: ${{ inputs.ssh-port }}
        KEY: ${{ inputs.ssh-key }}
        script: |
          IFS=',' read -r -a container_names <<< "${{ inputs.names }}"

          # Loop through each container name in the array
          for container in "${container_names[@]}"
          do
              echo "Stopping and removing containers with exact name: $container"

              # Find container IDs with exact name match
              container_ids=$(docker ps -aq --filter "name=^${container}$")

              if [ ! -z "$container_ids" ]; then
                  echo "Containers found for ${container}, stopping and removing..."
                  docker stop $container_ids
                  docker rm $container_ids
              else
                  echo "No containers found with the exact name: $container"
              fi
          done
