name: Deploy grafana (prod)
on:
  workflow_dispatch: null
  push:
    branches:
      - never
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stop old containers
        uses: ./.github/templates/stop-old-containers
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-key: ${{ secrets.SSH_KEY }}
          names: 'monitoring-grafana'
      - name: Deploy grafana
        uses: ./.github/templates/deploy-grafana
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-port: ${{ secrets.SSH_PORT }}
          ssh-key: ${{ secrets.SSH_KEY }}
          grafana-username: ${{ secrets.MONITORING_USERNAME }}
          grafana-password: ${{ secrets.MONITORING_PASSWORD }}
