name: Deploy frontend (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - never

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/magisterka-frontend-prod
      - name: Deploy
        uses: './.github/templates/deploy-container'
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          ssh-private-key: ${{ secrets.SSH_KEY }}
          server-port: 3000
          application-port: 3000
          image-name: ablaszkiewicz/magisterka-frontend-prod
          container-name: magisterka-frontend-prod
